wavesplatform/data-service

- src/db/__test__/sql/build/transactions/exchange/api.test.js
- src/db/__test__/sql/build/transactions/exchange/filters.test.js
- src/db/sql/build/transactions/exchange/api.js
- src/db/sql/build/transactions/exchange/filters.js
- src/db/sql/build/transactions/exchange/index.js
- src/db/sql/build/transactions/exchange/query.js
- src/endpoints/transactions/exchange/utils.js
- src/resolvers/transactions/exchange/validation/schema/many.js
- Optimized SQL query by moving txs + orders request to subquery and then apllying decimals join on the upper level
- Added `amountAsset` and `priceAsset` filters
> Data 63 exchange pair filter

- package.json
- src/endpoints/index.js
- src/endpoints/root.js
Added meta information to root endpoint
> Data 150 root endpoint

- src/services/candles/transformResults.js
> DATA-223-candles-result

- src/services/candles/schema.js
> DATA-222 candles service bugs fix

- src/services/candles/schema.js
add constraints for candles interval: 3h, 12h
fix checking divisibleByLeftBound param
> DATA-222 add constraints on available candles interval

- src/endpoints/transactions/index.js
- src/services/transactions/_common/commonFieldsSchemas.js
- src/services/transactions/all/commonData/schema.js
- src/services/transactions/all/index.js
- src/services/transactions/setAssetScript/__test__/__snapshots__/sql.test.js.snap
- src/services/transactions/setAssetScript/__test__/sql.test.js
- src/services/transactions/setAssetScript/index.js
- src/services/transactions/setAssetScript/schema.js
- src/services/transactions/setAssetScript/sql/filters.js
- src/services/transactions/setAssetScript/sql/index.js
- src/services/transactions/setAssetScript/sql/query.js
- src/services/transactions/setAssetScript/transformTxInfo.js
- add endpoint
- extend transactions service (set-asset-script and all parts)
> DATA-211 add set-asset-script type transactions

- package-lock.json
- package.json
- src/services/assets/__test__/__snapshots__/assets.test.js.snap
- src/services/assets/__test__/assets.test.js
- src/services/assets/schema.js
- src/services/assets/transformAsset.js
- src/services/transactions/__test__/integration/__snapshots__/transactions.test.int.js.snap
update assets service;
additionally update transactions int test (obsolete)
> DATA-230 add hasScript field for assets

- package.json
- src/services/assets/__test__/__snapshots__/assets.test.js.snap
- src/services/transactions/issue/schema.js
- src/services/transactions/issue/sql/filters.js
- src/services/transactions/issue/sql/query.js
update issue transactions: 
- add script field
- add filtering by script field
> DATA-211 update issue transactions

- src/services/candles/__test__/__snapshots__/candles.test.int.js.snap
- src/services/candles/transformResults.js
- src/services/presets/pg/getById/index.ts
- src/services/presets/pg/mgetByIds/index.ts
> Fix candles txs field

- src/services/presets/pg/searchWithPagination/__test__/validation.test.ts
- src/services/presets/pg/searchWithPagination/index.ts
- src/services/presets/pg/searchWithPagination/transformInput.ts
- src/services/presets/pg/searchWithPagination/transformResult.ts
https://jira.wavesplatform.com/browse/DATA-910
> DATA-910: last page detection

- src/services/transactions/exchange/schema.js
> DATA-929 OrderV3 - fix schema

- README.md
There we go, thats better. Though now my editor has removed some whitespace!
> Add DEFAULT_MATCHER to ReadMe Params

- src/endpoints/_common/many.js
- src/endpoints/_common/one.js
- src/endpoints/candles/search.js
- src/endpoints/matcher/pairs/many.js
- src/endpoints/matcher/pairs/one.js
- src/endpoints/matcher/rates/estimate.ts
- src/endpoints/pairs/many.js
- src/endpoints/pairs/one.js
- src/index.ts
- src/middleware/notFoundHandler.js
specific - 404 endpoint (system)
> fix json response

- src/services/pairs/index.ts
fixed pairs service is placed under v1
> pairs service backward compatibility fixed

- docs/openapi.json
- docs/openapi.yaml
- src/endpoints/transactions/index.ts
- src/services/transactions/_common/commonFieldsSchemas.js
- src/services/transactions/exchange/index.ts
- src/services/transactions/exchange/schema.js
- src/services/transactions/exchange/sql/filters.js
- src/services/transactions/massTransfer/sql/query.js
- fix bug; 
- clean mass-transfer txs; 
- clean docs
> fix bug; clean mass-transfer txs; clean docs

- src/services/assets/index.ts
- src/services/pairs/index.ts
Fixed caches for assets and pairs
> Data 1059 matcher validation asset existence fix

- src/services/transactions/data/pg/index.js
- src/services/transactions/data/schema.js
- src/utils/validation/joi.js
- add bignumber not NaN validation on search input;
- fix data txs db error handling.
> DATA-1082 data txs search bug

- src/services/index.ts
assets can be updated every 1 minute
> DATA-1096 decrease assets cache time

- src/services/assets/sql/searchAssets.ts
> DATA-1097 assets searching

- src/utils/db/index.js
fix search query preprocessing.
> search-query-fix: update query parsing

- src/daemons/candles/create.js
- src/daemons/pairs/create.js
- src/daemons/presets/daemon.js
- src/db/driver/pg.ts
- src/errorHandling/getErrorMessage.js
- src/loadConfig.ts
- fix daemons error reporting; 
- add pg statement timeout.
> DATA-1073 fix daemons

- src/utils/date/index.ts
- fix adding missing candles bug (date rounding to weeks)
> DATA-1137 fix week candles

- docs/openapi.json
- docs/openapi.yaml
> DATA-1134, 1135 update docs

- src/services/_common/presets/pg/search/transformResults.ts
> DATA-1152 search queries returns rows without one

- src/services/transactions/_common/sql/filters.js
- src/services/transactions/exchange/sql/query.js
- src/services/transactions/massTransfer/sql/query.js
- src/services/transactions/sponsorship/sql/query.js
- fix bug with exchange txs query;
- fix sponsorship txs query - make it faster
> DATA-965 fix txs sql query

- src/endpoints/matchers/rates/estimate.ts
> empty-pair-fix: defaulting to empty array for absent pairs

- docs/openapi.json
- docs/openapi.yaml
added:
-UTC reference
-post requests
-transactions requests by 'ids'
> DATA-1150,1153,1174 docs update

- docs/openapi.json
- docs/openapi.yaml
- package-lock.json
- package.json
- src/endpoints/aliases.js
- src/services/aliases/data/sql.js
- src/services/aliases/index.ts
- src/services/aliases/schema.js
- add addresses filter;
- add queries filter (query ~ addressOrAlias).
> DATA-1292 add aliases filters

- src/http/_common/filters/filters.ts
- src/http/pairs/utils.ts
> Pairs limit 1000
